name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test suite
    runs-on: ubuntu-latest
    container:
      image: php:7.1-cli-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install project dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === 'c5b9b6d368201a9db6f74e2611495f369991b72d9c8cbd3ffbc63edff210eb73d46ffbfce88669ad33695ef77dc76976') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php --filename=composer
          php -r "unlink('composer-setup.php');"
          php composer install
      - name: Run PHP Coding Standards Fixer tool
        run: |
          php ./vendor/bin/php-cs-fixer fix --dry-run --config=.php_cs.dist
      - name: Run phpstan
        run: |
          php ./vendor/bin/phpstan analyse src
      - name: Run Psalm
        run: |
          php ./vendor/bin/psalm
      - name: Run phpspec
        run: |
          php  ./vendor/bin/phpspec run
